//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eClub.L10nResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CCResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CCResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eClub.L10nResources.CCResources", typeof(CCResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficio.
        /// </summary>
        public static string benefit {
            get {
                return ResourceManager.GetString("benefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción del beneficio.
        /// </summary>
        public static string benefit_description {
            get {
                return ResourceManager.GetString("benefit_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividendos del beneficio.
        /// </summary>
        public static string benefit_dividends {
            get {
                return ResourceManager.GetString("benefit_dividends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia del Dividendo.
        /// </summary>
        public static string benefit_dividendsduration {
            get {
                return ResourceManager.GetString("benefit_dividendsduration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividendo máximo.
        /// </summary>
        public static string benefit_maxdividens {
            get {
                return ResourceManager.GetString("benefit_maxdividens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo por período.
        /// </summary>
        public static string benefit_maxperperiod {
            get {
                return ResourceManager.GetString("benefit_maxperperiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividendo mínimo.
        /// </summary>
        public static string benefit_mindividens {
            get {
                return ResourceManager.GetString("benefit_mindividens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string benefit_name {
            get {
                return ResourceManager.GetString("benefit_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodo inicial.
        /// </summary>
        public static string benefit_startperiod {
            get {
                return ResourceManager.GetString("benefit_startperiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frecuencia de uso.
        /// </summary>
        public static string benefit_usefrequency {
            get {
                return ResourceManager.GetString("benefit_usefrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string gen_Add {
            get {
                return ResourceManager.GetString("gen_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string gen_Back {
            get {
                return ResourceManager.GetString("gen_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string gen_Cancel {
            get {
                return ResourceManager.GetString("gen_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string gen_Delete {
            get {
                return ResourceManager.GetString("gen_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string gen_Edit {
            get {
                return ResourceManager.GetString("gen_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string gen_English {
            get {
                return ResourceManager.GetString("gen_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string gen_Enter {
            get {
                return ResourceManager.GetString("gen_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string gen_Save {
            get {
                return ResourceManager.GetString("gen_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string gen_Spanish {
            get {
                return ResourceManager.GetString("gen_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string gen_Submit {
            get {
                return ResourceManager.GetString("gen_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string loc_Start {
            get {
                return ResourceManager.GetString("loc_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingreso al sistema.
        /// </summary>
        public static string login_Access {
            get {
                return ResourceManager.GetString("login_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvidé mi password.
        /// </summary>
        public static string login_ForgotPassword {
            get {
                return ResourceManager.GetString("login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string login_Password {
            get {
                return ResourceManager.GetString("login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordarme.
        /// </summary>
        public static string login_Rememberme {
            get {
                return ResourceManager.GetString("login_Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string login_Username {
            get {
                return ResourceManager.GetString("login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia dividendos.
        /// </summary>
        public static string prod_DivDuration {
            get {
                return ResourceManager.GetString("prod_DivDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividendos por período.
        /// </summary>
        public static string prod_EarnedDividends {
            get {
                return ResourceManager.GetString("prod_EarnedDividends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividendo máximo.
        /// </summary>
        public static string prod_MaxDividends {
            get {
                return ResourceManager.GetString("prod_MaxDividends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad permitida.
        /// </summary>
        public static string prod_MaxProd {
            get {
                return ResourceManager.GetString("prod_MaxProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exoneración membresía.
        /// </summary>
        public static string prod_MemberFeeExon {
            get {
                return ResourceManager.GetString("prod_MemberFeeExon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membresía.
        /// </summary>
        public static string prod_MembershipFee {
            get {
                return ResourceManager.GetString("prod_MembershipFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividendo mínimo.
        /// </summary>
        public static string prod_MinDividends {
            get {
                return ResourceManager.GetString("prod_MinDividends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del producto.
        /// </summary>
        public static string prod_Name {
            get {
                return ResourceManager.GetString("prod_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exoneración cuota.
        /// </summary>
        public static string prod_PaymentExon {
            get {
                return ResourceManager.GetString("prod_PaymentExon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuota.
        /// </summary>
        public static string prod_PaymentFee {
            get {
                return ResourceManager.GetString("prod_PaymentFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frecuencia de pago.
        /// </summary>
        public static string prod_PaymentFreq {
            get {
                return ResourceManager.GetString("prod_PaymentFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anual.
        /// </summary>
        public static string prod_PaymentFreqAnnual {
            get {
                return ResourceManager.GetString("prod_PaymentFreqAnnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestral.
        /// </summary>
        public static string prod_PaymentFreqBiannual {
            get {
                return ResourceManager.GetString("prod_PaymentFreqBiannual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bimestral.
        /// </summary>
        public static string prod_PaymentFreqBimonthly {
            get {
                return ResourceManager.GetString("prod_PaymentFreqBimonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interanual.
        /// </summary>
        public static string prod_PaymentFreqInterannual {
            get {
                return ResourceManager.GetString("prod_PaymentFreqInterannual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensual.
        /// </summary>
        public static string prod_PaymentFreqMonthly {
            get {
                return ResourceManager.GetString("prod_PaymentFreqMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Único.
        /// </summary>
        public static string prod_PaymentFreqOnce {
            get {
                return ResourceManager.GetString("prod_PaymentFreqOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimestral.
        /// </summary>
        public static string prod_PaymentFreqQuarter {
            get {
                return ResourceManager.GetString("prod_PaymentFreqQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuatrimestral.
        /// </summary>
        public static string prod_PaymentFreqTriannual {
            get {
                return ResourceManager.GetString("prod_PaymentFreqTriannual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        public static string prod_Provider {
            get {
                return ResourceManager.GetString("prod_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado del Plan.
        /// </summary>
        public static string prod_Status {
            get {
                return ResourceManager.GetString("prod_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigente Hasta.
        /// </summary>
        public static string prod_ValidityEnd {
            get {
                return ResourceManager.GetString("prod_ValidityEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigente Desde.
        /// </summary>
        public static string prod_ValidityStart {
            get {
                return ResourceManager.GetString("prod_ValidityStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar en sistema.
        /// </summary>
        public static string prod_Viewable {
            get {
                return ResourceManager.GetString("prod_Viewable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar en Website.
        /// </summary>
        public static string prod_WebViewable {
            get {
                return ResourceManager.GetString("prod_WebViewable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string role_CanDelete {
            get {
                return ResourceManager.GetString("role_CanDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string role_CanEdit {
            get {
                return ResourceManager.GetString("role_CanEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string role_CanPrint {
            get {
                return ResourceManager.GetString("role_CanPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        public static string role_CanQuery {
            get {
                return ResourceManager.GetString("role_CanQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción del rol.
        /// </summary>
        public static string role_Description {
            get {
                return ResourceManager.GetString("role_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del rol.
        /// </summary>
        public static string role_Name {
            get {
                return ResourceManager.GetString("role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción de pantalla.
        /// </summary>
        public static string scr_File {
            get {
                return ResourceManager.GetString("scr_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de pantalla.
        /// </summary>
        public static string scr_Name {
            get {
                return ResourceManager.GetString("scr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiario.
        /// </summary>
        public static string subpr_Beneficiaries {
            get {
                return ResourceManager.GetString("subpr_Beneficiaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividendos por período.
        /// </summary>
        public static string subpr_Dividends {
            get {
                return ResourceManager.GetString("subpr_Dividends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia.
        /// </summary>
        public static string subpr_EndDate {
            get {
                return ResourceManager.GetString("subpr_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edad Máxima.
        /// </summary>
        public static string subpr_MaxAge {
            get {
                return ResourceManager.GetString("subpr_MaxAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto por Cliente.
        /// </summary>
        public static string subpr_MaxAmount {
            get {
                return ResourceManager.GetString("subpr_MaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edad mínima.
        /// </summary>
        public static string subpr_MinAge {
            get {
                return ResourceManager.GetString("subpr_MinAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string subpr_Name {
            get {
                return ResourceManager.GetString("subpr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        public static string subpr_PaymentAmt {
            get {
                return ResourceManager.GetString("subpr_PaymentAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exoneración.
        /// </summary>
        public static string subpr_PaymentExon {
            get {
                return ResourceManager.GetString("subpr_PaymentExon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string subpr_StartDate {
            get {
                return ResourceManager.GetString("subpr_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string subpr_Status {
            get {
                return ResourceManager.GetString("subpr_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subproducto.
        /// </summary>
        public static string subproduct {
            get {
                return ResourceManager.GetString("subproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        public static string user_Blocked {
            get {
                return ResourceManager.GetString("user_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eMail.
        /// </summary>
        public static string user_Email {
            get {
                return ResourceManager.GetString("user_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intentos fallidos.
        /// </summary>
        public static string user_FailedAttempts {
            get {
                return ResourceManager.GetString("user_FailedAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string user_FirstName {
            get {
                return ResourceManager.GetString("user_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string user_LastName {
            get {
                return ResourceManager.GetString("user_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string user_Phone {
            get {
                return ResourceManager.GetString("user_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia password.
        /// </summary>
        public static string user_PwdExpDate {
            get {
                return ResourceManager.GetString("user_PwdExpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string user_Username {
            get {
                return ResourceManager.GetString("user_Username", resourceCulture);
            }
        }
    }
}
